name: closr
description: A Closr Prototype App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^3.0.5
  firebase_analytics: ^1.0.3
  firebase_auth: ^0.5.20
  firebase_database: ^1.0.4
  firebase_storage: ^1.0.3
  cloud_firestore: ^0.7.4

  cupertino_icons: ^0.1.2

  fluttertoast: ^2.0.7
  shared_preferences: ^0.4.2
  cached_network_image: ^0.4.1
  intl: ^0.15.7
  flutter_swiper: ^1.1.4
  flutter_page_indicator:
  image_picker: ^0.4.10
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/diamond.png
    - asset/images/slanted_menu.png
    - asset/images/lee.png
    - asset/images/dev.png
    - asset/images/Closr_grey_01.png
    - asset/images/img_not_available.jpeg
    - asset/images/mimi1.gif
    - asset/images/mimi2.gif
    - asset/images/mimi3.gif
    - asset/images/mimi4.gif
    - asset/images/mimi5.gif
    - asset/images/mimi6.gif
    - asset/images/mimi7.gif
    - asset/images/mimi8.gif
    - asset/images/mimi9.gif
    - asset/images/bg.jpeg
    - asset/images/bg0.jpeg
    - asset/images/bg1.jpeg
    - asset/images/bg2.jpeg
    - asset/images/test.gif
    - asset/images/undraw_true_friends_c94g.svg

  fonts:
    - family: Rubik
      fonts:
        - asset: asset/fonts/Rubik-Regular.ttf
        - asset: asset/fonts/Rubik-Medium.ttf
          weight: 500
  #  - asset/images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
